services:
  pytorch-compiler:
    build:
      args:
        - BASE_IMAGE_NAME=nvcr.io/nvidia/pytorch:22.11-py3
    image: pytorch-compiler
    environment:
      - TORCHINDUCTOR_TRACE=0
      - TORCH_HOME=/workspace
      - DEBIAN_FRONTEND=noninteractive
    shm_size: 16g
    ulimits:
      memlock: -1
      stack: 67108864
    runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ["1"]
    #           capabilities: [gpu]
    # ports:
    #   - 8888:8888
    # entrypoint:
    #   [
    #     "jupyter",
    #     "lab",
    #     "--ServerApp.ip=0.0.0.0",
    #     "--ServerApp.port=8888",
    #     "--ServerApp.allow_root=True",
    #     "--ServerApp.token=''",
    #     "--ServerApp.password=''",
    #     "--Application.log_level='CRITICAL'",
    #   ]
    entrypoint: ["python3", "/workspace/run.py"]
    working_dir: /workspace
    volumes:
      - type: bind
        source: workspace
        target: /workspace
